apiVersion: cache.redrvm.cloud/v1alpha1
kind: Slck
metadata:
  labels:
    app.kubernetes.io/name: slck
    app.kubernetes.io/instance: slck-0
    app.kubernetes.io/part-of: slckop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slckop
  name: slck-0
spec:
  chartRepo: github.com/ccokee/slck-chart
  chartName: slck-chart
  chartVersion: "1"
  namespace: default
  values:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    image:
      repository: ccokee/slck
      pullPolicy: IfNotPresent
      tag: k9s
    imagePullSecrets: []
    replicas: 3
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
    nameOverride: ""
    fullnameOverride: ""
    service:
      type: ClusterIP
      port: 10443
    nodeSelector: {}
    tolerations: []
    affinity: {}
    redis:
      replicas: 1
      service:
        type: NodePort
        port: 6379
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
