---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cli.redrvm.cloud
  resources:
  - slcks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cli.redrvm.cloud
  resources:
  - slcks/finalizers
  verbs:
  - update
- apiGroups:
  - cli.redrvm.cloud
  resources:
  - slcks/status
  verbs:
  - get
  - patch
  - update
