# permissions for end users to edit slcks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slck-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slckop
    app.kubernetes.io/part-of: slckop
    app.kubernetes.io/managed-by: kustomize
  name: slck-editor-role
rules:
- apiGroups:
  - cache.redrvm.cloud
  resources:
  - slcks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.redrvm.cloud
  resources:
  - slcks/status
  verbs:
  - get
