# permissions for end users to view slcks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slck-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slck-operator
    app.kubernetes.io/part-of: slck-operator
    app.kubernetes.io/managed-by: kustomize
  name: slck-viewer-role
rules:
- apiGroups:
  - cli.redrvm.cloud
  resources:
  - slcks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cli.redrvm.cloud
  resources:
  - slcks/status
  verbs:
  - get
